version: '3.9'

services:
  db_auth:
    container_name: BankAppDb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:16.2-alpine3.19